import type { TrainingPlan } from "@/types";

export const TRAINING_PLANS: TrainingPlan[] = [
  {
    id: "ppl",
    name: "Push / Pull / Legs",
    description: "6 days per week. Classic split targeting push, pull, and leg movements twice each.",
    isPreset: true,
    days: [
      {
        dayOfWeek: 1,
        label: "Push",
        muscleGroups: ["chest", "shoulders", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex01", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex02", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex10", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex11", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex17", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 2,
        label: "Pull",
        muscleGroups: ["back", "biceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex05", defaultSets: 4, defaultReps: 6, defaultRestSeconds: 180 },
          { exerciseId: "ex07", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex08", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex12", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex14", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 3,
        label: "Legs",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex20", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 180 },
          { exerciseId: "ex22", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex21", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90 },
          { exerciseId: "ex24", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex25", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 4,
        label: "Push",
        muscleGroups: ["chest", "shoulders", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex02", defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex03", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex13", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex11", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex18", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
        ],
      },
      {
        dayOfWeek: 5,
        label: "Pull",
        muscleGroups: ["back", "biceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex06", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex09", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90 },
          { exerciseId: "ex07", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex12", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex15", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 6,
        label: "Legs",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex27", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex26", defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex23", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex24", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex30", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 0,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
    ],
  },
  {
    id: "arnold",
    name: "Arnold Split",
    description: "6 days per week. Chest & Back, Shoulders & Arms, Legs — repeated twice.",
    isPreset: true,
    days: [
      {
        dayOfWeek: 1,
        label: "Chest & Back",
        muscleGroups: ["chest", "back"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex01", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex06", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex02", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex07", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex03", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 2,
        label: "Shoulders & Arms",
        muscleGroups: ["shoulders", "biceps", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex10", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex11", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex14", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60 },
          { exerciseId: "ex17", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60 },
          { exerciseId: "ex18", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
        ],
      },
      {
        dayOfWeek: 3,
        label: "Legs",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex20", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 180 },
          { exerciseId: "ex22", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex21", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90 },
          { exerciseId: "ex26", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex25", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 4,
        label: "Chest & Back",
        muscleGroups: ["chest", "back"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex02", defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex08", defaultSets: 4, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex04", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex09", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex03", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 5,
        label: "Shoulders & Arms",
        muscleGroups: ["shoulders", "biceps", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex13", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex12", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
          { exerciseId: "ex16", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60 },
          { exerciseId: "ex19", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 60 },
          { exerciseId: "ex15", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 6,
        label: "Legs",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex27", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex23", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex24", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex26", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90 },
          { exerciseId: "ex30", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 0,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
    ],
  },
  {
    id: "upper-lower",
    name: "Upper / Lower",
    description: "4 days per week. Alternates upper and lower body with 3 rest days.",
    isPreset: true,
    days: [
      {
        dayOfWeek: 1,
        label: "Upper",
        muscleGroups: ["chest", "back", "shoulders", "biceps", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex01", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex07", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex10", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex14", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex17", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 2,
        label: "Lower",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex20", defaultSets: 4, defaultReps: 6, defaultRestSeconds: 180 },
          { exerciseId: "ex22", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex21", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 90 },
          { exerciseId: "ex26", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex25", defaultSets: 3, defaultReps: 15, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 3,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
      {
        dayOfWeek: 4,
        label: "Upper",
        muscleGroups: ["chest", "back", "shoulders", "biceps", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex02", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex06", defaultSets: 4, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex13", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex15", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex18", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
        ],
      },
      {
        dayOfWeek: 5,
        label: "Lower",
        muscleGroups: ["legs", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex27", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex23", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex24", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex05", defaultSets: 3, defaultReps: 6, defaultRestSeconds: 180 },
          { exerciseId: "ex30", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 6,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
      {
        dayOfWeek: 0,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
    ],
  },
  {
    id: "full-body",
    name: "Full Body",
    description: "3 days per week. Each session trains all major muscle groups with compound movements.",
    isPreset: true,
    days: [
      {
        dayOfWeek: 1,
        label: "Full Body A",
        muscleGroups: ["chest", "back", "legs", "shoulders", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex20", defaultSets: 4, defaultReps: 6, defaultRestSeconds: 180 },
          { exerciseId: "ex01", defaultSets: 3, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex07", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex10", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex28", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 2,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
      {
        dayOfWeek: 3,
        label: "Full Body B",
        muscleGroups: ["legs", "back", "chest", "biceps", "triceps"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex05", defaultSets: 4, defaultReps: 5, defaultRestSeconds: 180 },
          { exerciseId: "ex02", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex06", defaultSets: 3, defaultReps: 8, defaultRestSeconds: 120 },
          { exerciseId: "ex14", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex17", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 4,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
      {
        dayOfWeek: 5,
        label: "Full Body C",
        muscleGroups: ["legs", "shoulders", "back", "glutes", "core"],
        isRestDay: false,
        exercises: [
          { exerciseId: "ex27", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex13", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex09", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
          { exerciseId: "ex26", defaultSets: 3, defaultReps: 10, defaultRestSeconds: 90 },
          { exerciseId: "ex30", defaultSets: 3, defaultReps: 12, defaultRestSeconds: 60 },
        ],
      },
      {
        dayOfWeek: 6,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
      {
        dayOfWeek: 0,
        label: "Rest",
        muscleGroups: [],
        isRestDay: true,
        exercises: [],
      },
    ],
  },
];
